### ISSUE TITLE
Add example consumers and sinks

### ISSUE THREAD

**Issue by fschoell** [pinax-network/substreams-antelope#1]
- [ ] add a consumer example to retrieve data from the blocktime-meta substream
- [ ] add an example sink for the above substream
- [ ] add documentation on how to write custom consumers
- [ ] add documentation how to use the existing sinks
  - [ ] flat file
  - [ ] MongoDB
  - [ ] graph-node

**Comment by DenisCarriere** [comment]
This would be documented via StreamingFast docs or Graph docs
